spring.application.name=schoolbook_managementsystem
server.port=8081
spring.datasource.url=${DB_URL}

spring.datasource.username=${DB_USERNAME}

spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

# Disable Spring Boot DevTools automatic browser reload
spring.devtools.livereload.enabled=false